name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload artifact in batches
      run: |
        BATCH_SIZE=500
        FILES=($(find . -type f))
        TOTAL_FILES=${#FILES[@]}
        START=0

        while [ $START -lt $TOTAL_FILES ]; do
          END=$((START+BATCH_SIZE))
          if [ $END -gt $TOTAL_FILES ]; then
            END=$TOTAL_FILES
          fi
          BATCH_FILES=("${FILES[@]:$START:$BATCH_SIZE}")
          echo "Uploading files $START to $END out of $TOTAL_FILES"
          tar -czf batch_$START.tar.gz "${BATCH_FILES[@]}"
          gh upload-artifact --name batch_$START batch_$START.tar.gz
          START=$END
        done
      shell: bash

    - name: Deploy
      run: |
        # Aquí iría tu script de despliegue, dependiendo de cómo y dónde despliegues tu aplicación
